#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib


SX_SOURCE = r'''/* Generated by tools/probe_special_intrinsics.py. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <loongson-sxintrin.h>

static void print_bytes(const char *label, const void *value, unsigned long size)
{
    const unsigned char *bytes = (const unsigned char *)value;
    printf("%s:", label);
    for (unsigned long i = 0; i < size; i++)
        printf(" %02x", bytes[i]);
    putchar('\n');
}

static __m128i make_m128i(unsigned int seed)
{
    __m128i value;
    unsigned char *bytes = (unsigned char *)&value;
    for (unsigned long i = 0; i < sizeof(value); i++)
        bytes[i] = (unsigned char)(seed + i * 13u);
    return value;
}

static void fill_mem(unsigned char *mem, unsigned long size, unsigned int seed)
{
    for (unsigned long i = 0; i < size; i++)
        mem[i] = (unsigned char)(seed + i * 7u);
}

int main(void)
{
    unsigned char mem[96];
    __m128i a = make_m128i(17u);
    __m128i b = make_m128i(46u);
    __m128i r;

#define PROBE_EXTRINS(NAME, CALL, DST, SRC) \
    puts(NAME); \
    print_bytes("  arg0", &a, sizeof(a)); \
    print_bytes("  arg1", &b, sizeof(b)); \
    printf("  arg2=%llu\n", (unsigned long long)(DST)); \
    printf("  arg3=%llu\n", (unsigned long long)(SRC)); \
    r = CALL; \
    print_bytes("  out", &r, sizeof(r));

    PROBE_EXTRINS("__lsx_vextrins_b", __lsx_vextrins_b(a, b, 5, 9), 5, 9)
    PROBE_EXTRINS("__lsx_vextrins_h", __lsx_vextrins_h(a, b, 2, 6), 2, 6)
    PROBE_EXTRINS("__lsx_vextrins_w", __lsx_vextrins_w(a, b, 1, 3), 1, 3)
    PROBE_EXTRINS("__lsx_vextrins_d", __lsx_vextrins_d(a, b, 1, 0), 1, 0)

#undef PROBE_EXTRINS
#define PROBE_LOAD(NAME, CALL, OFFSET) \
    fill_mem(mem, sizeof(mem), 0x80u); \
    puts(NAME); \
    printf("  arg0=%llu\n", (unsigned long long)(OFFSET)); \
    print_bytes("  arg1", mem, 40); \
    r = CALL; \
    print_bytes("  out", &r, sizeof(r));

    PROBE_LOAD("__lsx_vblb", __lsx_vblb(3, mem), 3)
    PROBE_LOAD("__lsx_vblh", __lsx_vblh(4, mem), 4)
    PROBE_LOAD("__lsx_vblw", __lsx_vblw(8, mem), 8)
    PROBE_LOAD("__lsx_vbld", __lsx_vbld(16, mem), 16)

#undef PROBE_LOAD
#define PROBE_STORE(NAME, CALL, LANE, OFFSET) \
    fill_mem(mem, sizeof(mem), 0x20u); \
    puts(NAME); \
    print_bytes("  arg0", &a, sizeof(a)); \
    printf("  arg1=%llu\n", (unsigned long long)(LANE)); \
    printf("  arg2=%llu\n", (unsigned long long)(OFFSET)); \
    print_bytes("  arg3", mem, 40); \
    CALL; \
    print_bytes("  out", mem, 40);

    PROBE_STORE("__lsx_vsb", __lsx_vsb(a, 2, 4, mem), 2, 4)
    PROBE_STORE("__lsx_vsh", __lsx_vsh(a, 3, 8, mem), 3, 8)
    PROBE_STORE("__lsx_vsw", __lsx_vsw(a, 1, 12, mem), 1, 12)
    PROBE_STORE("__lsx_vsd", __lsx_vsd(a, 1, 16, mem), 1, 16)

    return 0;
}
'''


ASX_SOURCE = r'''/* Generated by tools/probe_special_intrinsics.py. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <loongson-asxintrin.h>

static void print_bytes(const char *label, const void *value, unsigned long size)
{
    const unsigned char *bytes = (const unsigned char *)value;
    printf("%s:", label);
    for (unsigned long i = 0; i < size; i++)
        printf(" %02x", bytes[i]);
    putchar('\n');
}

static __m256i make_m256i(unsigned int seed)
{
    __m256i value;
    unsigned char *bytes = (unsigned char *)&value;
    for (unsigned long i = 0; i < sizeof(value); i++)
        bytes[i] = (unsigned char)(seed + i * 13u);
    return value;
}

static __m256i make_all_zero(void)
{
    __m256i value;
    memset(&value, 0, sizeof(value));
    return value;
}

static __m256i make_one_byte(void)
{
    __m256i value = make_all_zero();
    ((unsigned char *)&value)[3] = 1;
    return value;
}

static __m256i make_all_nonzero(void)
{
    __m256i value;
    memset(&value, 1, sizeof(value));
    return value;
}

static void fill_mem(unsigned char *mem, unsigned long size, unsigned int seed)
{
    for (unsigned long i = 0; i < size; i++)
        mem[i] = (unsigned char)(seed + i * 7u);
}

int main(void)
{
    unsigned char mem[128];
    __m256i a = make_m256i(17u);
    __m256i b = make_m256i(46u);
    __m256i r;
    int s;

#define PROBE_EXTRINS(NAME, CALL, DST, SRC) \
    puts(NAME); \
    print_bytes("  arg0", &a, sizeof(a)); \
    print_bytes("  arg1", &b, sizeof(b)); \
    printf("  arg2=%llu\n", (unsigned long long)(DST)); \
    printf("  arg3=%llu\n", (unsigned long long)(SRC)); \
    r = CALL; \
    print_bytes("  out", &r, sizeof(r));

    PROBE_EXTRINS("__lasx_mxvextrins_b", __lasx_mxvextrins_b(a, b, 5, 9), 5, 9)
    PROBE_EXTRINS("__lasx_mxvextrins_h", __lasx_mxvextrins_h(a, b, 2, 6), 2, 6)
    PROBE_EXTRINS("__lasx_mxvextrins_w", __lasx_mxvextrins_w(a, b, 1, 3), 1, 3)
    PROBE_EXTRINS("__lasx_mxvextrins_d", __lasx_mxvextrins_d(a, b, 1, 0), 1, 0)

#undef PROBE_EXTRINS
#define PROBE_BRANCH(NAME, VALUE, CALL) \
    do { \
        __m256i bv = VALUE; \
        puts(NAME); \
        print_bytes("  arg0", &bv, sizeof(bv)); \
        s = CALL; \
        printf("  out=%lld\n", (long long)s); \
    } while (0);

    PROBE_BRANCH("__lasx_xbz_v", make_all_zero(), __lasx_xbz_v(bv))
    PROBE_BRANCH("__lasx_xbz_v", make_one_byte(), __lasx_xbz_v(bv))
    PROBE_BRANCH("__lasx_xbz_b", make_all_zero(), __lasx_xbz_b(bv))
    PROBE_BRANCH("__lasx_xbz_b", make_one_byte(), __lasx_xbz_b(bv))
    PROBE_BRANCH("__lasx_xbz_b", make_all_nonzero(), __lasx_xbz_b(bv))
    PROBE_BRANCH("__lasx_xbz_h", make_all_zero(), __lasx_xbz_h(bv))
    PROBE_BRANCH("__lasx_xbz_h", make_one_byte(), __lasx_xbz_h(bv))
    PROBE_BRANCH("__lasx_xbz_h", make_all_nonzero(), __lasx_xbz_h(bv))
    PROBE_BRANCH("__lasx_xbz_w", make_all_zero(), __lasx_xbz_w(bv))
    PROBE_BRANCH("__lasx_xbz_w", make_one_byte(), __lasx_xbz_w(bv))
    PROBE_BRANCH("__lasx_xbz_w", make_all_nonzero(), __lasx_xbz_w(bv))
    PROBE_BRANCH("__lasx_xbz_d", make_all_zero(), __lasx_xbz_d(bv))
    PROBE_BRANCH("__lasx_xbz_d", make_one_byte(), __lasx_xbz_d(bv))
    PROBE_BRANCH("__lasx_xbz_d", make_all_nonzero(), __lasx_xbz_d(bv))
    PROBE_BRANCH("__lasx_xbnz_v", make_all_zero(), __lasx_xbnz_v(bv))
    PROBE_BRANCH("__lasx_xbnz_v", make_one_byte(), __lasx_xbnz_v(bv))
    PROBE_BRANCH("__lasx_xbnz_b", make_all_zero(), __lasx_xbnz_b(bv))
    PROBE_BRANCH("__lasx_xbnz_b", make_one_byte(), __lasx_xbnz_b(bv))
    PROBE_BRANCH("__lasx_xbnz_b", make_all_nonzero(), __lasx_xbnz_b(bv))
    PROBE_BRANCH("__lasx_xbnz_h", make_all_zero(), __lasx_xbnz_h(bv))
    PROBE_BRANCH("__lasx_xbnz_h", make_one_byte(), __lasx_xbnz_h(bv))
    PROBE_BRANCH("__lasx_xbnz_h", make_all_nonzero(), __lasx_xbnz_h(bv))
    PROBE_BRANCH("__lasx_xbnz_w", make_all_zero(), __lasx_xbnz_w(bv))
    PROBE_BRANCH("__lasx_xbnz_w", make_one_byte(), __lasx_xbnz_w(bv))
    PROBE_BRANCH("__lasx_xbnz_w", make_all_nonzero(), __lasx_xbnz_w(bv))
    PROBE_BRANCH("__lasx_xbnz_d", make_all_zero(), __lasx_xbnz_d(bv))
    PROBE_BRANCH("__lasx_xbnz_d", make_one_byte(), __lasx_xbnz_d(bv))
    PROBE_BRANCH("__lasx_xbnz_d", make_all_nonzero(), __lasx_xbnz_d(bv))

#undef PROBE_BRANCH
#define PROBE_LOAD(NAME, CALL, OFFSET) \
    fill_mem(mem, sizeof(mem), 0x80u); \
    puts(NAME); \
    printf("  arg0=%llu\n", (unsigned long long)(OFFSET)); \
    print_bytes("  arg1", mem, 48); \
    r = CALL; \
    print_bytes("  out", &r, sizeof(r));

    PROBE_LOAD("__lasx_xvld_b", __lasx_xvld_b(3, mem), 3)
    PROBE_LOAD("__lasx_xvblb", __lasx_xvblb(3, mem), 3)
    PROBE_LOAD("__lasx_xvblh", __lasx_xvblh(4, mem), 4)
    PROBE_LOAD("__lasx_xvblw", __lasx_xvblw(8, mem), 8)
    PROBE_LOAD("__lasx_xvbld", __lasx_xvbld(16, mem), 16)

#undef PROBE_LOAD
#define PROBE_STORE(NAME, CALL, LANE, OFFSET) \
    fill_mem(mem, sizeof(mem), 0x20u); \
    puts(NAME); \
    print_bytes("  arg0", &a, sizeof(a)); \
    printf("  arg1=%llu\n", (unsigned long long)(LANE)); \
    printf("  arg2=%llu\n", (unsigned long long)(OFFSET)); \
    print_bytes("  arg3", mem, 48); \
    CALL; \
    print_bytes("  out", mem, 48);

    PROBE_STORE("__lasx_xvsb", __lasx_xvsb(a, 2, 4, mem), 2, 4)
    PROBE_STORE("__lasx_xvsh", __lasx_xvsh(a, 3, 8, mem), 3, 8)
    PROBE_STORE("__lasx_xvsw", __lasx_xvsw(a, 1, 12, mem), 1, 12)
    PROBE_STORE("__lasx_xvsd", __lasx_xvsd(a, 1, 16, mem), 1, 16)
    puts("__lasx_xvst_b");
    fill_mem(mem, sizeof(mem), 0x20u);
    print_bytes("  arg0", &a, sizeof(a));
    printf("  arg1=%llu\n", (unsigned long long)5);
    print_bytes("  arg2", mem, 48);
    __lasx_xvst_b(a, 5, mem);
    print_bytes("  out", mem, 48);

    return 0;
}
'''


MSA_SOURCE = r'''/* Generated by tools/probe_special_intrinsics.py. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <msa.h>

static void print_bytes(const char *label, const void *value, unsigned long size)
{
    const unsigned char *bytes = (const unsigned char *)value;
    printf("%s:", label);
    for (unsigned long i = 0; i < size; i++)
        printf(" %02x", bytes[i]);
    putchar('\n');
}

static v16i8 make_v16i8(unsigned int seed)
{
    v16i8 value;
    unsigned char *bytes = (unsigned char *)&value;
    for (unsigned long i = 0; i < sizeof(value); i++)
        bytes[i] = (unsigned char)(seed + i * 13u);
    return value;
}

static v16u8 make_all_zero(void)
{
    v16u8 value;
    memset(&value, 0, sizeof(value));
    return value;
}

static v16u8 make_one_byte(void)
{
    v16u8 value = make_all_zero();
    ((unsigned char *)&value)[3] = 1;
    return value;
}

static v16u8 make_all_nonzero(void)
{
    v16u8 value;
    memset(&value, 1, sizeof(value));
    return value;
}

static void fill_mem(unsigned char *mem, unsigned long size, unsigned int seed)
{
    for (unsigned long i = 0; i < size; i++)
        mem[i] = (unsigned char)(seed + i * 7u);
}

int main(void)
{
    unsigned char mem[96];
    v16i8 a = make_v16i8(17u);
    v16u8 bv;
    int s;

#define PROBE_LOAD(NAME, TYPE, CALL, OFFSET) \
    do { \
        TYPE r; \
        fill_mem(mem, sizeof(mem), 0x80u); \
        puts(NAME); \
        print_bytes("  arg0", mem, 40); \
        printf("  arg1=%llu\n", (unsigned long long)(OFFSET)); \
        r = CALL; \
        print_bytes("  out", &r, sizeof(r)); \
    } while (0);

    PROBE_LOAD("__msa_ld_b", v16i8, __msa_ld_b(mem, 5), 5)
    PROBE_LOAD("__msa_ld_h", v8i16, __msa_ld_h(mem, 6), 6)
    PROBE_LOAD("__msa_ld_w", v4i32, __msa_ld_w(mem, 8), 8)
    PROBE_LOAD("__msa_ld_d", v2i64, __msa_ld_d(mem, 16), 16)

#undef PROBE_LOAD
#define PROBE_STORE(NAME, CALL, OFFSET) \
    fill_mem(mem, sizeof(mem), 0x20u); \
    puts(NAME); \
    print_bytes("  arg0", &a, sizeof(a)); \
    print_bytes("  arg1", mem, 40); \
    printf("  arg2=%llu\n", (unsigned long long)(OFFSET)); \
    CALL; \
    print_bytes("  out", mem, 40);

    PROBE_STORE("__msa_st_b", __msa_st_b(a, mem, 5), 5)
    PROBE_STORE("__msa_st_h", __msa_st_h((v8i16)a, mem, 6), 6)
    PROBE_STORE("__msa_st_w", __msa_st_w((v4i32)a, mem, 8), 8)
    PROBE_STORE("__msa_st_d", __msa_st_d((v2i64)a, mem, 16), 16)

#undef PROBE_STORE
#define PROBE_BRANCH(NAME, VALUE, CALL) \
    do { \
        bv = VALUE; \
        puts(NAME); \
        print_bytes("  arg0", &bv, sizeof(bv)); \
        s = CALL; \
        printf("  out=%lld\n", (long long)s); \
    } while (0);

    PROBE_BRANCH("__msa_test_bz_v", make_all_zero(), __msa_test_bz_v(bv))
    PROBE_BRANCH("__msa_test_bz_v", make_one_byte(), __msa_test_bz_v(bv))
    PROBE_BRANCH("__msa_test_bz_b", make_all_zero(), __msa_test_bz_b(bv))
    PROBE_BRANCH("__msa_test_bz_b", make_one_byte(), __msa_test_bz_b(bv))
    PROBE_BRANCH("__msa_test_bz_b", make_all_nonzero(), __msa_test_bz_b(bv))
    PROBE_BRANCH("__msa_test_bz_h", make_all_zero(), __msa_test_bz_h((v8u16)bv))
    PROBE_BRANCH("__msa_test_bz_h", make_one_byte(), __msa_test_bz_h((v8u16)bv))
    PROBE_BRANCH("__msa_test_bz_h", make_all_nonzero(), __msa_test_bz_h((v8u16)bv))
    PROBE_BRANCH("__msa_test_bz_w", make_all_zero(), __msa_test_bz_w((v4u32)bv))
    PROBE_BRANCH("__msa_test_bz_w", make_one_byte(), __msa_test_bz_w((v4u32)bv))
    PROBE_BRANCH("__msa_test_bz_w", make_all_nonzero(), __msa_test_bz_w((v4u32)bv))
    PROBE_BRANCH("__msa_test_bz_d", make_all_zero(), __msa_test_bz_d((v2u64)bv))
    PROBE_BRANCH("__msa_test_bz_d", make_one_byte(), __msa_test_bz_d((v2u64)bv))
    PROBE_BRANCH("__msa_test_bz_d", make_all_nonzero(), __msa_test_bz_d((v2u64)bv))
    PROBE_BRANCH("__msa_test_bnz_v", make_all_zero(), __msa_test_bnz_v(bv))
    PROBE_BRANCH("__msa_test_bnz_v", make_one_byte(), __msa_test_bnz_v(bv))
    PROBE_BRANCH("__msa_test_bnz_b", make_all_zero(), __msa_test_bnz_b(bv))
    PROBE_BRANCH("__msa_test_bnz_b", make_one_byte(), __msa_test_bnz_b(bv))
    PROBE_BRANCH("__msa_test_bnz_b", make_all_nonzero(), __msa_test_bnz_b(bv))
    PROBE_BRANCH("__msa_test_bnz_h", make_all_zero(), __msa_test_bnz_h((v8u16)bv))
    PROBE_BRANCH("__msa_test_bnz_h", make_one_byte(), __msa_test_bnz_h((v8u16)bv))
    PROBE_BRANCH("__msa_test_bnz_h", make_all_nonzero(), __msa_test_bnz_h((v8u16)bv))
    PROBE_BRANCH("__msa_test_bnz_w", make_all_zero(), __msa_test_bnz_w((v4u32)bv))
    PROBE_BRANCH("__msa_test_bnz_w", make_one_byte(), __msa_test_bnz_w((v4u32)bv))
    PROBE_BRANCH("__msa_test_bnz_w", make_all_nonzero(), __msa_test_bnz_w((v4u32)bv))
    PROBE_BRANCH("__msa_test_bnz_d", make_all_zero(), __msa_test_bnz_d((v2u64)bv))
    PROBE_BRANCH("__msa_test_bnz_d", make_one_byte(), __msa_test_bnz_d((v2u64)bv))
    PROBE_BRANCH("__msa_test_bnz_d", make_all_nonzero(), __msa_test_bnz_d((v2u64)bv))

    puts("__msa_cfcmsa");
    printf("  arg0=%llu\n", (unsigned long long)1);
    printf("  out=%lld\n", (long long)__msa_cfcmsa(1));

    return 0;
}
'''


CSR_SOURCE = r'''/* Generated by tools/probe_special_intrinsics.py. */
#include <stdint.h>
#include <stdio.h>
#include <sys/wait.h>
#include <unistd.h>
#include <loongson-csr.h>

__attribute__((used)) static int compile_rdcsr(void) { return __lcsr_rdcsr(0); }
__attribute__((used)) static long compile_drdcsr(void) { return __lcsr_drdcsr(0); }
__attribute__((used)) static int compile_rdgcsr(void) { return __lcsr_rdgcsr(0); }
__attribute__((used)) static long compile_drdgcsr(void) { return __lcsr_drdgcsr(0); }
__attribute__((used)) static void compile_wrcsr(void) { __lcsr_wrcsr(0, 0); }
__attribute__((used)) static void compile_dwrcsr(void) { __lcsr_dwrcsr(0, 0); }
__attribute__((used)) static void compile_wrgcsr(void) { __lcsr_wrgcsr(0, 0); }
__attribute__((used)) static void compile_dwrgcsr(void) { __lcsr_dwrgcsr(0, 0); }

static void run_scalar(const char *name, long arg, long out)
{
    puts(name);
    printf("  arg0=%lld\n", (long long)arg);
    printf("  out=%lld\n", (long long)out);
}

static void not_user_safe(const char *name)
{
    puts(name);
    printf("  out=%lld\n", (long long)-254);
}

static void run_maybe_trap(const char *name, long arg, long (*fn)(void))
{
    int pipefd[2];
    if (pipe(pipefd) != 0)
        return;
    pid_t pid = fork();
    if (pid == 0) {
        close(pipefd[0]);
        long out = fn();
        write(pipefd[1], &out, sizeof(out));
        close(pipefd[1]);
        _exit(0);
    }
    close(pipefd[1]);
    long out = 0;
    ssize_t got = read(pipefd[0], &out, sizeof(out));
    close(pipefd[0]);
    int status = 0;
    waitpid(pid, &status, 0);
    puts(name);
    printf("  arg0=%lld\n", (long long)arg);
    if (WIFEXITED(status) && WEXITSTATUS(status) == 0 && got == (ssize_t)sizeof(out))
        printf("  out=%lld\n", (long long)out);
    else if (WIFSIGNALED(status))
        printf("  out=%lld\n", (long long)(-WTERMSIG(status)));
    else
        printf("  out=%lld\n", (long long)-255);
}

static long rdcsr0(void) { return __lcsr_rdcsr(0); }
static long drdcsr0(void) { return __lcsr_drdcsr(0); }
static long rdgcsr0(void) { return __lcsr_rdgcsr(0); }
static long drdgcsr0(void) { return __lcsr_drdgcsr(0); }

int main(void)
{
    run_scalar("__lcsr_cpucfg", 0, __lcsr_cpucfg(0));
    run_scalar("__lcsr_cpucfg", 1, __lcsr_cpucfg(1));
    run_scalar("__lcsr_rdtimel", 0, __lcsr_rdtimel().value);
    run_scalar("__lcsr_rdtimeh", 0, __lcsr_rdtimeh().value);
    run_scalar("__lcsr_drdtime", 0, __lcsr_drdtime().dvalue);
    run_maybe_trap("__lcsr_rdcsr", 0, rdcsr0);
    run_maybe_trap("__lcsr_drdcsr", 0, drdcsr0);
    run_maybe_trap("__lcsr_rdgcsr", 0, rdgcsr0);
    run_maybe_trap("__lcsr_drdgcsr", 0, drdgcsr0);
    not_user_safe("__lcsr_lwdir");
    not_user_safe("__lcsr_lddir");
    not_user_safe("__lcsr_lwpte");
    not_user_safe("__lcsr_ldpte");

    puts("__lcsr_wrcsr");
    printf("  arg0=%lld\n", (long long)0);
    printf("  arg1=%lld\n", (long long)0);
    printf("  out=%lld\n", (long long)-254);
    puts("__lcsr_dwrcsr");
    printf("  arg0=%lld\n", (long long)0);
    printf("  arg1=%lld\n", (long long)0);
    printf("  out=%lld\n", (long long)-254);
    puts("__lcsr_wrgcsr");
    printf("  arg0=%lld\n", (long long)0);
    printf("  arg1=%lld\n", (long long)0);
    printf("  out=%lld\n", (long long)-254);
    puts("__lcsr_dwrgcsr");
    printf("  arg0=%lld\n", (long long)0);
    printf("  arg1=%lld\n", (long long)0);
    printf("  out=%lld\n", (long long)-254);

    return 0;
}
'''


SOURCES = {
    "sx": SX_SOURCE,
    "asx": ASX_SOURCE,
    "msa": MSA_SOURCE,
    "csr": CSR_SOURCE,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate special-case C probes for skipped intrinsics."
    )
    parser.add_argument("--output-dir", required=True, type=pathlib.Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for key, source in SOURCES.items():
        path = args.output_dir / f"probe_special_{key}.c"
        path.write_text(source)
        print(f"{key}: wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
